name: CI Build and Test

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug - List files in working directory
        run: |
          pwd
          ls -al


      - name: Build Docker images
        run: docker-compose build
        working-directory: .

      - name: Run backend tests
        run: |
          cd backend
          docker-compose run --rm backend poetry run python manage.py test

      - name: Run frontend tests
        run: |
          cd frontend
          docker-compose run --rm frontend npm test
      - name: List built images (for verification)
        run: docker images
        working-directory: .
      - name: Tag and Push Docker images
        run: |
          # Tag les images avec le nom du registre et le SHA du commit
          docker tag mon_livre_recettes-backend:latest ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          docker tag mon_livre_recettes-frontend:latest ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          # Pousse les images
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
        working-directory: .

      - name: List built images (for verification)
        run: docker images
